import { CarProps } from "@/types";

//footerlinks
export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Business Relation", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Invite Friends", url: "/" },
    ],
  },
  {
    title: "Social",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];

//Cars and Manufacturers list
export const manufacturers = [
  { name: "Model S", manufacturer: "Tesla" },
  { name: "Civic", manufacturer: "Honda" },
  { name: "Corolla", manufacturer: "Toyota" },
  { name: "Mustang", manufacturer: "Ford" },
  { name: "911", manufacturer: "Porsche" },
  { name: "A4", manufacturer: "Audi" },
  { name: "C-Class", manufacturer: "Mercedes-Benz" },
  { name: "Camaro", manufacturer: "Chevrolet" },
  { name: "Altima", manufacturer: "Nissan" },
  { name: "Impreza", manufacturer: "Subaru" },
  { name: "Golf", manufacturer: "Volkswagen" },
  { name: "3 Series", manufacturer: "BMW" },
  { name: "Challenger", manufacturer: "Dodge" },
  { name: "Elantra", manufacturer: "Hyundai" },
  { name: "F-Type", manufacturer: "Jaguar" },
  { name: "Sorento", manufacturer: "Kia" },
  { name: "CX-5", manufacturer: "Mazda" },
  { name: "V60", manufacturer: "Volvo" },
  { name: "Impreza WRX", manufacturer: "Subaru" },
  { name: "Qashqai", manufacturer: "Nissan" },
  { name: "Optima", manufacturer: "Kia" },
  { name: "Accord", manufacturer: "Honda" },
  { name: "X5", manufacturer: "BMW" },
  { name: "Tahoe", manufacturer: "Chevrolet" },
  { name: "Range Rover", manufacturer: "Land Rover" },
  { name: "500", manufacturer: "Fiat" },
  { name: "Huracan", manufacturer: "Lamborghini" },
  { name: "Panamera", manufacturer: "Porsche" },
  { name: "Quattroporte", manufacturer: "Maserati" },
  { name: "S60", manufacturer: "Volvo" },
];

//dummy car list
export const carList: CarProps[] = [
  {
    city_mpg: 25,
    class: "SUV",
    combination_mpg: 28,
    cylinders: 4,
    driver: "AWD",
    fuel_type: 1,
    highway_mpg: 30,
    make: "Toyota",
    model: "RAV4",
    transmission: "Automatic",
    year: "2021",
    path: "/prado.png",
  },
  {
    city_mpg: 20,
    class: "Sedan",
    combination_mpg: 24,
    cylinders: 6,
    driver: "FWD",
    fuel_type: 1,
    highway_mpg: 27,
    make: "Honda",
    model: "Accord",
    transmission: "Manual",
    year: "2020",
    path: "/prado.png",
  },
  {
    city_mpg: 18,
    class: "Truck",
    combination_mpg: 22,
    cylinders: 8,
    driver: "4WD",
    fuel_type: 2,
    highway_mpg: 25,
    make: "Ford",
    model: "F-150",
    transmission: "Automatic",
    year: "2022",
    path: "/benz2.jpg",
  },
  {
    city_mpg: 23,
    class: "Sedan",
    combination_mpg: 26,
    cylinders: 4,
    driver: "FWD",
    fuel_type: 1,
    highway_mpg: 29,
    make: "Nissan",
    model: "Altima",
    transmission: "Automatic",
    year: "2021",
    path: "/porche.jpg",
  },
  {
    city_mpg: 28,
    class: "Hatchback",
    combination_mpg: 32,
    cylinders: 4,
    driver: "FWD",
    fuel_type: 1,
    highway_mpg: 36,
    make: "Volkswagen",
    model: "Golf",
    transmission: "Manual",
    year: "2019",
    path: "/range.jpg",
  },
  {
    city_mpg: 19,
    class: "SUV",
    combination_mpg: 21,
    cylinders: 6,
    driver: "AWD",
    fuel_type: 1,
    highway_mpg: 24,
    make: "Chevrolet",
    model: "Tahoe",
    transmission: "Automatic",
    year: "2020",
    path: "/discovery.jpg",
  },
  {
    city_mpg: 30,
    class: "Compact",
    combination_mpg: 33,
    cylinders: 3,
    driver: "FWD",
    fuel_type: 1,
    highway_mpg: 38,
    make: "BMW",
    model: "i3",
    transmission: "Automatic",
    year: "2021",
    path: "/bmw.jpg",
  },
  {
    city_mpg: 24,
    class: "Crossover",
    combination_mpg: 28,
    cylinders: 4,
    driver: "AWD",
    fuel_type: 1,
    highway_mpg: 32,
    make: "Hyundai",
    model: "Tucson",
    transmission: "Automatic",
    year: "2022",
    path: "/benz1.jpg",
  },
  {
    city_mpg: 16,
    class: "SUV",
    combination_mpg: 19,
    cylinders: 8,
    driver: "4WD",
    fuel_type: 2,
    highway_mpg: 22,
    make: "Jeep",
    model: "Grand Cherokee",
    transmission: "Automatic",
    year: "2020",
    path: "/range.jpg",
  },
  {
    city_mpg: 35,
    class: "Hybrid",
    combination_mpg: 40,
    cylinders: 4,
    driver: "FWD",
    fuel_type: 1,
    highway_mpg: 44,
    make: "Toyota",
    model: "Prius",
    transmission: "Automatic",
    year: "2019",
    path: "/prado.png",
  },
  {
    city_mpg: 27,
    class: "Sedan",
    combination_mpg: 31,
    cylinders: 4,
    driver: "FWD",
    fuel_type: 1,
    highway_mpg: 35,
    make: "Mazda",
    model: "Mazda3",
    transmission: "Manual",
    year: "2021",
    path: "/discovery.jpg",
  },
  {
    city_mpg: 22,
    class: "SUV",
    combination_mpg: 25,
    cylinders: 6,
    driver: "AWD",
    fuel_type: 2,
    highway_mpg: 28,
    make: "GMC",
    model: "Acadia",
    transmission: "Automatic",
    year: "2021",
    path: "/benz2.jpg",
  },
  {
    city_mpg: 33,
    class: "Hatchback",
    combination_mpg: 37,
    cylinders: 4,
    driver: "FWD",
    fuel_type: 1,
    highway_mpg: 41,
    make: "Honda",
    model: "Civic",
    transmission: "Manual",
    year: "2020",
    path: "/bmw.jpg",
  },
  {
    city_mpg: 21,
    class: "Luxury",
    combination_mpg: 24,
    cylinders: 6,
    driver: "AWD",
    fuel_type: 1,
    highway_mpg: 27,
    make: "Audi",
    model: "Q5",
    transmission: "Automatic",
    year: "2022",
    path: "/discovery.jpg",
  },
  {
    city_mpg: 14,
    class: "Truck",
    combination_mpg: 17,
    cylinders: 8,
    driver: "4WD",
    fuel_type: 2,
    highway_mpg: 20,
    make: "Ram",
    model: "1500",
    transmission: "Automatic",
    year: "2020",
    path: "/porche.jpg",
  },
];
